### PR TITLE
Reorganize servers

### PR DESCRIPTION
**Pull request by KorvinSzanto**
I kept all of your code, just moved it around slightly. Let me know if there's anything in here that you don't like
- Rename to \Concrete\Core\Service
- Use interfaces instead of abstracts
- Bind to classname instead of abstract string
- Separate naming and handling concerns
- Separate detection concerns

Todo:
- Get this stuff tested4

### CODE REVIEW

**Comment by KorvinSzanto** [comment]
Removed the $_SERVER dependency, now it goes through the DI request instance

**Comment by mlocati** [comment]
I really don't understand why to read/write 10 lines of code in .htaccess we need 12 classes... I think that after this pretty-url related stuff I'm going to give up with core-related stuff...

**Comment by KorvinSzanto** [comment]
Why merge if you weren't comfortable with the content? I hope you understand that this is a community effort, I'm not trying to dictate the implementation I'm trying to help with the architecture of it.

These things are broken out into their individual responsibilities, you don't need "12 classes" to generate htaccess content, you just need a single class (Look at ApacheGenerator). The other classes are for detecting what service we're running or managing the services. At the very very least this makes our code 100% testable. At most, this allows us to do some really interesting things in terms of detecting the current environment and generating configuration.

Hopefully we can have a generic detector and a generic service that you can simply configure to return the single class you create which is the generator.

``` php
$service = new \Concrete\GenericService(new \my\CustomGenerator(), new \Concrete\CallableDetector(function() {
     return ...;
});
$manager->extend('apache', $service);
```

To me this isn't much different than what we had before, it's just separating concerns.

**Comment by mlocati** [comment]
> Why merge if you weren't comfortable with the content?

Would you have accepted a PR otherwise?

**Comment by KorvinSzanto** [comment]
That is up to andy, not me. I'm sure if you and others are saying that this solution is the right one, he'll listen to you over me like he has done many many times in the past :P

All I want to do here is help work out the best possible way to implement this feature, do you have any specific gripes with the implementation that I have other than that I have interfaces and two new classes now? What would you change?

**Comment by KorvinSzanto** [comment]
@mlocati another thing to point out is that you can do what you have already just by implementing all three interfaces:

``` php
<?php

class FooService implements ServiceInterface, GeneratorInterface, DetectorInterface
{
    public function getGenerator() { return $this; }
    public function getDetector() { return $this; }

    public function detect() {
        ...
    }

    public function generate() {
        ...
    }

}
```

**Comment by mlocati** [comment]
@ KorvinSzanto what about the way I'm implementing this?
The dashboard page is almost functional.
I still have to do some work for nginx, but Apache should work.
What about CLI? A new command maybe?

**Pull request merged**
